### POST register
POST http://localhost:8080/api/user/register
Host: localhost:8080
Content-Type: application/json

{
  "login": "solo",
  "password": "12345"
}

### POST authentication solo
POST http://localhost:8080/api/user/login
Host: localhost:8080
Content-Type: application/json
Cookie: ErrAuth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6Im5leHQifQ.uFayTG0yvMcs3py3M6-PbOZQUcznJTXVIo5RQLBokv8

{
  "login": "next",
  "password": "12345"
}

### POST authentication solo
POST http://localhost:8080/api/user/login
Host: localhost:8080
Content-Type: application/json
Cookie: ErrAuth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6InNvbG8ifQ.rLfRajrW0gUYnVIEkTLGCCqhFHfQvDMkFHLoO6fo0y0

{
  "login": "solo",
  "password": "12345"
}

### POST request with cookie passed through headers and data in the body
POST http://localhost:8080/api/user/orders
Host: localhost:8080
Content-Type: text/plain

#12345678903
#31722088874
#2377225624
88070083642064

### POST списание бонусов
POST  http://localhost:8080/api/user/balance/withdraw
Host: localhost:8080
Content-Type: application/json

{
  "order": "88070083642064",
  "sum": 203
}


### Get orders
GET http://localhost:8080/api/user/orders

### Get balance
GET http://localhost:8080/api/user/balance

### Get withdrawals
GET http://localhost:8080/api/user/withdrawals



