### POST save
POST http://localhost:8080/
Host: localhost:8080
Content-Type: text/plain

https://google.com


### POST register
POST http://localhost:8080/api/user/register
Host: localhost:8080
Content-Type: application/json

{
  "login": "nextb",
  "password": "123df23"
}

### Get
# @no-redirect
GET http://localhost:8080/2qEhT1TF


### POST authentication
POST http://localhost:8080/api/user/login
Host: localhost:8080
Content-Type: application/json
Cookie: Auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.LUue-nOzj5c_K77ecItY_79bdQADQ303TdjYohC5B_g

{
  "login": "nextbug",
  "password": "5uZY84aP"
}

### POST authentication
POST http://localhost:8080/api/user/login
Host: localhost:8080
Content-Type: application/json

{
  "login": "user1",
  "password": "12345"
}

### GET request with cookie passed through headers
# @no-redirect
GET http://localhost:8080/api/user/urls
Cookie: Auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.LUue-nOzj5c_K77ecItY_79bdQADQ303TdjYohC5B_g
