### POST register
POST http://localhost:8080/api/user/register
Host: localhost:8080
Content-Type: application/json

{
  "login": "solo",
  "password": "12345"
}

### POST authentication solo
POST http://localhost:8080/api/user/login
Host: localhost:8080
Content-Type: application/json
CCookie: Auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6InVzZXIzIn0.lX5RePcCJDkQkp8isPU2MHJ7WZ5l7jq4x93jKg4Fg1I

{
  "login": "user3",
  "password": "12345"
}

### POST authentication solo
POST http://localhost:8080/api/user/login
Host: localhost:8080
Content-Type: application/json
Cookie: Auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6InNvbG8ifQ.rLfRajrW0gUYnVIEkTLGCCqhFHfQvDMkFHLoO6fo0y0

{
  "login": "solo",
  "password": "12345"
}


### Get orders
GET http://localhost:8080/api/user/orders

### Get balance
GET http://localhost:8080/api/user/balance



### POST request with cookie passed through headers and data in the body
POST http://localhost:8080/api/user/orders
Host: localhost:8080
Content-Type: text/plain

#12345678903
#31722088874
2377225624

### POST списание бонусов
POST  http://localhost:8080/api/user/balance/withdraw
Host: localhost:8080
Content-Type: application/json

{
  "order": "1641562",
  "sum": 71
}
